export type SiteFaqPageKey =
  | "home"
  | "platform"
  | "pricing"
  | "billingPayments"
  | "aiClaimAnalysis"
  | "clientPortal"
  | "claimTracking"
  | "communicationHub"
  | "roofing"
  | "commercial"
  | "waterDamage"
  | "fireDamage"
  | "mold"
  | "contents"
  | "about"
  | "contact"
  | "partnerNetwork"
  | "reviews"
  | "blog"
  | "guides"
  | "caseStudies"
  | "videos";

export type SiteFaqConfig = {
  topic: string;
  faqIds: readonly string[];
};

export const SITE_FAQ: Record<SiteFaqPageKey, SiteFaqConfig> = {
  home: {
    topic: "Claims Ninja",
    faqIds: [
      "getting-started-who-for",
      "getting-started-onboarding",
      "supplements-whats-included",
      "pricing-fee-structure",
      "carrier-how-handled",
      "ai-how-helps",
      "carrier-public-adjuster",
    ],
  },
  platform: {
    topic: "the Claims Ninja platform",
    faqIds: [
      "getting-started-who-for",
      "getting-started-field-vs-support",
      "platform-data-secure",
      "platform-access-controls",
      "platform-claim-tracking",
      "platform-communication",
      "supplements-whats-included",
      "carrier-public-adjuster",
    ],
  },
  pricing: {
    topic: "Claims Ninja pricing and billing",
    faqIds: [
      "pricing-fee-structure",
      "pricing-estimate-writing",
      "pricing-minimum-fees",
      "pricing-15-percent",
      "pricing-4-percent-rcv",
      "pricing-payment-processing",
      "pricing-when-charged",
      "pricing-additional-services",
    ],
  },
  billingPayments: {
    topic: "billing and payments",
    faqIds: [
      "billing-how-paid",
      "billing-percentage-charged",
      "billing-upfront-fees",
      "billing-fee-calculated",
      "billing-payment-due",
      "billing-long-term-contracts",
      "billing-selective-claims",
      "billing-replace-estimator",
    ],
  },
  aiClaimAnalysis: {
    topic: "AI claim analysis",
    faqIds: [
      "ai-how-helps",
      "ai-replace-experts",
      "ai-accuracy",
      "ai-what-analyzed",
      "ai-data-privacy",
      "help-missed-line-items",
    ],
  },
  clientPortal: {
    topic: "the client portal",
    faqIds: [
      "platform-access-controls",
      "documentation-platform-upload",
      "platform-data-secure",
      "getting-started-intake-info",
      "getting-started-first-claim",
    ],
  },
  claimTracking: {
    topic: "claim tracking",
    faqIds: [
      "platform-claim-tracking",
      "carrier-timeline",
      "supplements-turnaround",
      "carrier-who-talks",
      "documentation-essentials",
    ],
  },
  communicationHub: {
    topic: "carrier communication",
    faqIds: [
      "platform-communication",
      "carrier-who-talks",
      "carrier-how-handled",
      "carrier-timeline",
      "carrier-disputes",
    ],
  },
  roofing: {
    topic: "roofing claims",
    faqIds: [
      "roofing-carrier-documentation",
      "roofing-storm-vs-retail",
      "roofing-code-items",
      "roofing-commercial",
      "roofing-measurements",
      "roofing-op",
      "supplements-whats-included",
      "roof-matching-insurance-claim",
      "roof-matching-contractor-documentation",
      "roof-matching-dispute-photos",
      "roof-matching-supplement-denials",
      "roof-matching-discontinued-shingles",
      "roof-repairability-insurance-claim",
      "roof-repairability-contractor-documentation",
      "roof-brittle-test-roofing",
      "roof-repairability-documentation-evidence",
      "roof-repairability-carrier-disputes",
      "roof-reinspection-when-request",
      "roof-reinspection-documentation-prep",
      "roof-reinspection-missed-damage",
      "roof-reinspection-denial-reasons",
      "roof-reinspection-organize-photos",
      "roof-hail-vs-wind-documentation",
      "roof-layered-tear-off-discovery",
      "roof-flashing-supplement-qualification",
      "roof-commercial-damage-documentation",
      "roof-commercial-supplement-documentation",
      "roof-commercial-moisture-survey-payment",
      "roof-commercial-inspection-photos",
      "roof-commercial-system-replacement-documentation",
      "roof-hoa-responsible-damage",
      "roof-hoa-insurance-covers-replacement",
      "roof-hoa-damage-documentation",
      "roof-hoa-partial-building-replacement",
      "roof-hoa-supplement-documentation",
      "roof-multi-building-carrier-handling",
      "roof-multi-building-partial-replacement",
      "roof-multi-building-apartment-documentation",
      "roof-multi-building-matching",
      "roof-multi-building-supplement-documentation",
    ],
  },
  commercial: {
    topic: "commercial insurance claims",
    faqIds: [
      "commercial-claims-handled",
      "commercial-large-loss-support",
      "commercial-property-types-supported",
      "commercial-apartment-complex-claims",
      "commercial-national-restoration-programs",
      "commercial-claim-documentation",
      "commercial-large-loss-project-documentation",
      "commercial-multi-building-documentation",
      "commercial-tenant-improvements-documentation",
      "commercial-insurance-documentation-requirements",
      "fire-commercial-claims-documentation",
      "water-commercial-claims-documentation",
      "roof-commercial-damage-documentation",
      "water-large-loss-qualifies",
      "results-insights-commercial-portfolios",
    ],
  },
  waterDamage: {
    topic: "water damage claims",
    faqIds: [
      "water-mitigation-scope",
      "water-drying-documentation",
      "resources-water-mitigation-documentation",
      "water-category-class",
      "water-rebuild-supplements",
      "water-emergency-vs-rebuild",
      "water-commercial-losses",
      "water-commercial-claims-documentation",
      "water-apartment-loss-documentation",
      "water-multifamily-loss-documentation",
      "water-commercial-claims-scrutiny",
      "water-commercial-mitigation-package",
      "water-tenant-impact-documentation",
      "water-business-interruption-documentation",
      "water-commercial-claims-underpaid",
      "water-category-3-qualifies",
      "water-category-3-documentation-required",
      "water-moisture-maps-required",
      "water-dry-log-update-frequency",
      "water-equipment-charge-reductions",
      "water-final-mitigation-package",
      "water-daily-monitoring-records-importance",
      "water-claim-denied-documentation",
      "water-mitigation-file-documentation",
      "water-moisture-readings-importance",
      "water-missing-daily-monitoring",
      "water-final-drying-verification",
      "water-apartment-complex-documentation",
      "water-apartment-unit-separate-tracking",
      "water-apartment-equipment-usage-documentation",
      "water-apartment-mitigation-claims-disputed",
      "water-apartment-tenant-impact-required",
      "water-multifamily-claims-underpaid",
      "water-multifamily-units-documentation",
      "water-multifamily-equipment-reductions",
      "water-multifamily-tenant-impact-documentation",
      "water-multifamily-full-payment-support",
      "water-mitigation-invoice-reductions",
      "water-mitigation-invoice-documentation",
      "water-defend-drying-day-charges",
      "water-equipment-invoice-documentation",
      "water-mitigation-invoice-review-failures",
      "water-commercial-documentation-missing",
      "water-commercial-invoice-reduced-why",
      "water-commercial-tenant-impact-required",
      "water-commercial-common-area-documentation",
      "water-commercial-documentation-invoice-match",
      "water-large-loss-qualifies",
      "water-large-loss-documentation",
      "water-large-loss-scrutiny",
      "water-large-loss-drying-zones",
      "water-large-loss-invoice-documentation",
      "water-class-4-drying-definition",
      "water-class-4-documentation-required",
      "water-class-4-specialty-equipment-documentation",
      "water-class-4-drying-duration",
      "water-class-4-carrier-disputes",
      "water-reinspection-when-request",
      "water-reinspection-documentation-prep",
      "water-reinspection-additional-damage-documented",
      "water-reinspection-denial-reasons",
      "water-reinspection-organize-documentation",
    ],
  },
  fireDamage: {
    topic: "fire damage claims",
    faqIds: [
      "fire-damage-documentation-insurance",
      "fire-damage-photos-required",
      "fire-smoke-damage-insurance-coverage",
      "fire-hidden-damage-documentation",
      "fire-supplement-documentation-support",
      "smoke-damage-documentation-insurance",
      "soot-damage-insurance-coverage",
      "smoke-damage-photos-required",
      "smoke-damage-clean-vs-replace",
      "smoke-damage-supplement-documentation",
      "contents-inventory-documentation-insurance",
      "contents-inventory-insurance-required",
      "contents-smoke-damage-documentation",
      "contents-clean-vs-replace",
      "contents-supplement-documentation",
      "pack-out-documentation-insurance",
      "pack-out-chain-of-custody-documentation",
      "pack-out-storage-tracking",
      "pack-out-charges-documentation",
      "pack-out-return-documentation",
      "fire-claims-underpaid-why",
      "fire-claim-documentation-required",
      "fire-supplement-contractor-documentation",
      "fire-claim-documentation-delays",
      "fire-claim-documentation-improve",
      "fire-smoke-soot",
      "resources-fire-damage-documentation",
      "fire-structural-vs-contents",
      "fire-demo-rebuild",
      "fire-odor-deodorization",
      "fire-total-loss-partial",
      "fire-commercial-claims-documentation",
      "fire-commercial-tenant-owner-responsibility",
      "fire-commercial-large-loss-scrutiny",
      "fire-commercial-business-interruption-role",
      "fire-commercial-supplement-opportunities",
      "fire-code-upgrade-insurance-coverage",
      "fire-ordinance-law-coverage",
      "fire-code-upgrade-contractor-documentation",
      "fire-code-upgrade-who-determines-required",
      "fire-code-upgrade-supplement-denials",
      "fire-supplement-included-items",
      "fire-supplement-when-to-submit",
      "fire-supplement-documentation-evidence",
      "fire-supplement-multiple-submissions",
      "fire-supplement-commonly-missed-items",
      "smoke-damage-contractor-documentation-insurance",
      "smoke-damage-claim-photos-required",
      "smoke-damage-hvac-documentation-required",
      "smoke-damage-claims-underpaid-why",
      "smoke-damage-invisible-without-soot",
      "fire-supplement-checklist-documents",
      "fire-claim-photo-volume",
      "fire-smoke-documentation-support",
      "fire-hidden-damage-required",
      "fire-carrier-additional-documentation-why",
      "fire-supplement-denied-why",
      "fire-supplement-denial-missing-documentation",
      "fire-supplement-denial-response",
      "fire-supplement-denial-additional-docs",
      "fire-supplement-denial-common-reason",
    ],
  },
  mold: {
    topic: "mold claims",
    faqIds: [
      "mold-remediation-docs",
      "mold-testing",
      "mold-carrier-pushback",
      "mold-containment-equipment",
      "mold-water-relationship",
      "mold-supplement-included-items",
      "mold-supplement-when-to-submit",
      "mold-supplement-documentation-evidence",
      "mold-supplement-multiple-submissions",
      "mold-supplement-commonly-missed-items",
      "mold-supplement-checklist-documents",
      "mold-claim-photo-volume",
      "mold-moisture-containment-documentation-support",
      "mold-daily-progress-documentation-required",
      "mold-carrier-additional-documentation-why",
      "mold-supplement-denied-why",
      "mold-supplement-denial-documentation-gaps",
      "mold-supplement-denial-carrier-objections",
      "mold-supplement-denial-estimate-support",
      "mold-supplement-denial-reinspection",
    ],
  },
  contents: {
    topic: "contents restoration",
    faqIds: [
      "contents-pack-out",
      "pack-out-documentation-insurance",
      "pack-out-storage-tracking",
      "pack-out-charges-documentation",
      "contents-inventory",
      "contents-storage",
      "contents-specialty-items",
      "contents-fire-water",
    ],
  },
  about: {
    topic: "Claims Ninja",
    faqIds: [
      "getting-started-who-for",
      "getting-started-onboarding",
      "getting-started-field-vs-support",
      "carrier-public-adjuster",
      "platform-data-secure",
      "supplements-whats-included",
    ],
  },
  contact: {
    topic: "contacting Claims Ninja",
    faqIds: [
      "contact-response-time",
      "contact-multiple-claims",
      "contact-carrier-estimate",
      "getting-started-who-for",
      "getting-started-onboarding",
    ],
  },
  partnerNetwork: {
    topic: "partnering with Claims Ninja",
    faqIds: [
      "partner-network-strategic-partners",
      "partner-network-services-required",
      "partner-network-how-selected",
      "partner-network-request-introduction",
      "partner-network-who-eligible",
      "partner-network-financing",
      "partner-network-legal-partner",
      "partner-network-911-restoration",
      "partner-network-become-partner",
    ],
  },
  reviews: {
    topic: "contractor reviews and partnerships",
    faqIds: [
      "getting-started-who-for",
      "supplements-whats-included",
      "supplements-turnaround",
      "carrier-how-handled",
      "carrier-timeline",
    ],
  },
  blog: {
    topic: "contractor claims operations",
    faqIds: [
      "resources-water-mitigation-documentation",
      "fire-damage-documentation-insurance",
      "resources-fire-damage-documentation",
      "fire-claims-underpaid-why",
      "smoke-damage-claims-underpaid-why",
      "fire-supplement-checklist-documents",
      "fire-claim-photo-volume",
      "help-denied-supplements",
      "fire-supplement-denied-why",
      "fire-supplement-denial-missing-documentation",
      "fire-supplement-denial-response",
      "fire-supplement-denial-additional-docs",
      "fire-supplement-denial-common-reason",
      "supplements-whats-included",
      "documentation-essentials",
      "mold-claims-underpaid-why",
      "mold-documentation-affects-claim-outcomes",
      "mold-moisture-readings-settlement-support",
      "mold-hidden-damage-affects-payment",
      "mold-documentation-improves-settlement",
      "mold-common-documentation-mistakes",
      "mold-poor-documentation-reduces-payment",
      "mold-moisture-readings-why-important",
      "mold-claim-documentation-organization",
      "mold-documentation-package-contents",
      "mold-supplement-checklist-documents",
      "mold-claim-photo-volume",
      "mold-moisture-containment-documentation-support",
      "mold-daily-progress-documentation-required",
      "mold-carrier-additional-documentation-why",
      "mold-supplement-denied-why",
      "mold-supplement-denial-documentation-gaps",
      "mold-supplement-denial-carrier-objections",
      "mold-supplement-denial-estimate-support",
      "mold-supplement-denial-reinspection",
    ],
  },
  guides: {
    topic: "claims documentation and supplements",
    faqIds: [
      "documentation-essentials",
      "fire-damage-documentation-insurance",
      "fire-commercial-claims-documentation",
      "fire-commercial-large-loss-scrutiny",
      "fire-supplement-documentation-support",
      "fire-supplement-included-items",
      "fire-supplement-when-to-submit",
      "fire-supplement-documentation-evidence",
      "fire-supplement-multiple-submissions",
      "fire-supplement-commonly-missed-items",
      "fire-supplement-checklist-documents",
      "fire-carrier-additional-documentation-why",
      "fire-code-upgrade-contractor-documentation",
      "fire-code-upgrade-supplement-denials",
      "fire-supplement-denied-why",
      "fire-supplement-denial-common-reason",
      "fire-supplement-denial-missing-documentation",
      "fire-ordinance-law-coverage",
      "supplements-process",
      "documentation-photos",
      "getting-started-onboarding",
      "supplements-documentation",
      "help-denied-supplements",
      "roof-commercial-damage-documentation",
      "roof-commercial-supplement-documentation",
      "roof-commercial-moisture-survey-payment",
      "roof-hoa-damage-documentation",
      "roof-hoa-supplement-documentation",
      "roof-multi-building-apartment-documentation",
      "roof-multi-building-supplement-documentation",
      "water-dry-log-contents",
      "water-moisture-map-contents",
      "mold-remediation-docs",
      "mold-testing",
      "mold-carrier-pushback",
      "mold-containment-equipment",
      "mold-water-relationship",
      "mold-damage-documentation-insurance",
      "mold-claim-photos-required",
      "mold-moisture-readings-support",
      "mold-insurance-documentation-required",
      "mold-hidden-damage-documentation",
      "mold-remediation-work-documentation",
      "mold-remediation-photos-required",
      "mold-remediation-moisture-readings-support",
      "mold-remediation-insurance-documentation",
      "mold-remediation-containment-documentation",
      "mold-prv-definition",
      "mold-prv-documentation-insurance",
      "mold-prv-moisture-readings-required",
      "mold-prv-closeout-package",
      "mold-prv-clearance-documentation-required",
      "mold-protocol-definition",
      "mold-protocol-follow-exactly",
      "mold-protocol-change-documentation",
      "mold-protocol-supporting-documentation",
      "mold-protocol-field-conditions-differ",
      "mold-iaq-documentation",
      "mold-iaq-air-sampling",
      "mold-iaq-clearance-testing",
      "mold-iaq-lab-reports",
      "mold-iaq-documentation-requirements",
      "mold-claims-underpaid-why",
      "mold-documentation-affects-claim-outcomes",
      "mold-moisture-readings-settlement-support",
      "mold-hidden-damage-affects-payment",
      "mold-documentation-improves-settlement",
      "mold-common-documentation-mistakes",
      "mold-poor-documentation-reduces-payment",
      "mold-moisture-readings-why-important",
      "mold-claim-documentation-organization",
      "mold-documentation-package-contents",
      "mold-supplement-checklist-documents",
      "mold-claim-photo-volume",
      "mold-moisture-containment-documentation-support",
      "mold-daily-progress-documentation-required",
      "mold-carrier-additional-documentation-why",
      "mold-supplement-denied-why",
      "mold-supplement-denial-documentation-gaps",
      "mold-supplement-denial-carrier-objections",
      "mold-supplement-denial-estimate-support",
      "mold-supplement-denial-reinspection",
      "mold-commercial-claims-vs-residential",
      "mold-commercial-documentation-organization",
      "mold-commercial-multi-unit-documentation",
      "mold-commercial-insurance-documentation",
      "mold-commercial-phased-remediation",
      "mold-supplement-included-items",
      "mold-supplement-when-to-submit",
      "mold-supplement-documentation-evidence",
      "mold-supplement-multiple-submissions",
      "mold-supplement-commonly-missed-items",
    ],
  },
  caseStudies: {
    topic: "Results & Insights and recovery outcomes",
    faqIds: [
      "results-insights-what-is-page",
      "results-insights-real-examples",
      "results-insights-recovery-increase",
      "results-insights-trade-opportunities",
      "results-insights-portfolio-review",
      "results-insights-common-issues",
      "results-insights-commercial-portfolios",
      "results-insights-book-of-business",
    ],
  },
  videos: {
    topic: "the Claims Ninja platform",
    faqIds: [
      "getting-started-onboarding",
      "platform-claim-tracking",
      "ai-how-helps",
      "platform-communication",
      "getting-started-first-claim",
    ],
  },
} as const;

export function getSiteFaqConfig(key: SiteFaqPageKey): SiteFaqConfig {
  return SITE_FAQ[key];
}
