import { callout, defineArticle, h, p, ul } from "@/lib/help-center/builder";

const UPDATED = "2026-06-08";

export const operationsArticles = [
  defineArticle({
    slug: "cm-core-standard",
    sectionSlug: "claims-operations",
    title: "CM Core Standard (Non-Negotiable)",
    excerpt: "Move files forward — everything else is secondary.",
    portal: "internal",
    roles: ["cm"],
    updatedAt: UPDATED,
    blocks: [
      callout("critical", "Moving files forward is your primary job. Everything else is secondary. Passive waiting is failure."),
      p("Our 21-day average closure only works if EVERY file moves EVERY 2 days. Stalled files = unhappy clients = failed business."),
    ],
  }),
  defineArticle({
    slug: "cm-constant-rules",
    sectionSlug: "claims-operations",
    title: "CM Constant Rules",
    excerpt: "Annotation, communication, 5-minute rule, and system funneling.",
    portal: "internal",
    roles: ["cm"],
    updatedAt: UPDATED,
    blocks: [
      ul([
        "CONSTANT ANNOTATION — take notes on all things always",
        "ALWAYS inform clients and policyholders of updates, even if no update (ball on a hill)",
        "ALWAYS respond to team messages with thumbs up",
        "5-minute rule — if it takes 5 min, do it then and there",
        "ALWAYS schedule follow-up for any task when merited",
        "ALWAYS unread messages if opened and not yours when merited",
        "ALWAYS immediately add all project materials to appropriate locations if not uploaded correctly",
        "Funnel everyone through our systems while making them feel it takes load off their plates",
      ]),
    ],
  }),
  defineArticle({
    slug: "working-hours-schedule",
    sectionSlug: "claims-operations",
    title: "Working Hours & Weekly Schedule",
    excerpt: "8 AM start, time blocks, team meetings, and escalation windows.",
    portal: "internal",
    roles: ["cm", "tl"],
    updatedAt: UPDATED,
    blocks: [
      h(3, "Working Hours"),
      ul([
        "Start 8:00 AM local time — logged in and actively working",
        "Ready to engage clients and adjusters immediately",
        "No exceptions without prior approval",
      ]),
      h(3, "Time Management"),
      ul([
        "7–12ish: claims settlement",
        "12ish–5ish: estimates",
        "Finish current task before next unless major fire",
      ]),
      h(3, "CM Weekly Schedule"),
      ul([
        "8:00 AM: Get after it",
        "11:00 AM M/W/F: Team meetings",
        "Individual meetings as needed",
      ]),
      h(3, "TL Fires"),
      p("Always come with 2 potential solutions. M–F working hours."),
      h(3, "COO Fires"),
      p("Always come with 2 potential solutions. W–F: 12–2:30 and 3:30–5 EST. M–T: 12–5 EST. Call anytime for mega emergencies (COO is PST)."),
    ],
  }),
  defineArticle({
    slug: "two-day-contact-cycle",
    sectionSlug: "claims-operations",
    title: "Two-Day Contact Cycle",
    excerpt: "Every active claim must have meaningful progress within 2 days.",
    portal: "internal",
    roles: ["cm"],
    updatedAt: UPDATED,
    blocks: [
      callout("critical", "Every active claim in your workload must have meaningful progress within 2 days."),
      h(3, "Adjuster Contact"),
      ul([
        "MUST reach out via phone to every adjuster on active claims",
        "Contact cycle resets every 2 days maximum",
        "Phone contact required — emails alone don't count",
      ]),
      h(3, "Client Updates via Monday"),
      ul([
        "Update EVERY active claim in Monday.com within 2 days",
        "Updates must reflect real progress on the file",
      ]),
      h(3, "What Counts as Progress"),
      ul([
        "Reached out to adjuster via call, text, email; left voicemail; NA yet",
        "Spoke with adjuster, discussed line items, waiting on response by [date]",
        "Escalated to adjuster's supervisor",
        "Sent supplement with supporting documentation",
        "Scheduled inspection",
        "Obtained additional vendor quotes",
        "Filed formal escalation / appraisal demand",
        "Any action that moves the claim toward settlement",
      ]),
      h(3, "Daily Action Checklist"),
      ul([
        "Start at 8:00 AM sharp",
        "Review all active claims",
        "Identify files needing contact (2-day rule)",
        "Call, text, email every adjuster on those files",
        "Update Monday.com with meaningful progress",
        "Document next action and deadline for each file",
      ]),
    ],
  }),
  defineArticle({
    slug: "final-operating-principles",
    sectionSlug: "claims-operations",
    title: "Final Operating Principles",
    excerpt: "Core doctrine for claims operations.",
    portal: "internal",
    roles: ["all"],
    updatedAt: UPDATED,
    blocks: [
      ul([
        "Files move every 2 days",
        "Communication is proactive",
        "Documentation wins negotiations",
        "Escalation is strategic",
        "Speed + defensibility = profitability",
        "Compliance protects the company",
        "Systems create scale",
      ]),
    ],
  }),
];
