import { callout, defineArticle, h, link, p, ul, video } from "@/lib/help-center/builder";
import { EXTERNAL_LINKS, INTERNAL_LOOM_VIDEOS } from "@/lib/help-center/videos";

const UPDATED = "2026-06-08";

export const sopArticles = [
  defineArticle({
    slug: "per-touch-standard",
    sectionSlug: "sop-library",
    title: "Per Touch Standard",
    excerpt: "Every touch must move the claim forward.",
    portal: "internal",
    roles: ["cm"],
    updatedAt: UPDATED,
    blocks: [
      ul([
        "Check call/VM/text/email for updates",
        "If need more info, see More Info Request SOP",
        "Appropriate touches: adjuster, supervisors, agents, vendors, client/policyholder",
        "Update client, policyholder, and agent (if merited)",
      ]),
      callout("critical", "Every touch must move the claim forward."),
    ],
  }),
  defineArticle({
    slug: "na-communication-timeline",
    sectionSlug: "sop-library",
    title: "Claims Timeline if NA Communication",
    excerpt: "Escalation timeline when adjusters are non-responsive.",
    portal: "internal",
    roles: ["cm"],
    updatedAt: UPDATED,
    blocks: [
      ul([
        "Call, text, email adjuster daily (72 hr)",
        "Call, text, email supervisor daily (48 hr)",
        "Call, text, email agent daily (48 hr)",
        "Alert TL of imminent escalation",
        "Once permitted: escalation threat communication daily",
        "Alert policyholder of escalation strategy",
        "Create and send escalation evidence complaint packet for DOI submission",
      ]),
    ],
  }),
  defineArticle({
    slug: "escalation-triggers",
    sectionSlug: "sop-library",
    title: "Escalation Triggers to Leadership",
    excerpt: "When to escalate to your Team Leader.",
    portal: "internal",
    roles: ["cm"],
    updatedAt: UPDATED,
    blocks: [
      ul([
        "Client expressing dissatisfaction",
        "Claim stuck for more than 7 days with no progress",
        "Adjuster being unreasonable",
        "Settlement offer significantly below expectations",
        "Any situation that might result in losing client",
      ]),
    ],
  }),
  defineArticle({
    slug: "how-to-do-requests",
    sectionSlug: "sop-library",
    title: "How/When to Do Requests",
    excerpt: "Submit a Monday Request when progress is blocked at your level.",
    portal: "internal",
    roles: ["cm"],
    updatedAt: UPDATED,
    blocks: [
      video(INTERNAL_LOOM_VIDEOS.requests.url, INTERNAL_LOOM_VIDEOS.requests.title),
      p("Submit a Request when an issue cannot be solved at your level and is preventing progress."),
      ul([
        "Claim movement is blocked",
        "Leadership approval or decision required",
        "PA, Appraiser, or Attorney involvement needed",
        "Client escalation or exception approval required",
        "TL guidance does not resolve the issue",
        "Internal system issue prevents execution",
      ]),
      p("Attempt resolution first and come with 2 proposed solutions when possible."),
    ],
  }),
  defineArticle({
    slug: "viable-estimate-checklist",
    sectionSlug: "sop-library",
    title: "Viable Estimate Info Checklist",
    excerpt: "First thing to check on a new project assignment.",
    portal: "internal",
    roles: ["cm"],
    updatedAt: UPDATED,
    blocks: [
      ul([
        "Contract with ICA, AOB, Appraiser Authorization",
        "Sufficient files (not screenshots)",
        "Sufficient photos and job notes",
        "Sketch + measurements (L×W×H)",
        "Insurance estimate, policy, claim #",
        "Adjuster name, phone, email",
        "Job site distance from office",
        "If mit: demo sheets, dry logs",
        "Coverage endorsements reviewed",
        "Policy conditions noted",
        "Documentation organized defensibly",
        "Appraisal clause verified when relevant",
      ]),
    ],
  }),
  defineArticle({
    slug: "client-info-request",
    sectionSlug: "sop-library",
    title: "Client/Policyholder Info Request",
    excerpt: "3-day Monday contact cycle then call/VM/text daily.",
    portal: "internal",
    roles: ["cm"],
    updatedAt: UPDATED,
    blocks: [
      ul([
        "Request from appropriate party",
        "Contact via Monday daily for 3 business days",
        "If NA: Call → VM → Text daily until received",
        "If scheduled delivery date provided, hold until due date then continue",
        "Receive, ensure properly inputted, submit",
      ]),
    ],
  }),
  defineArticle({
    slug: "insurance-info-request",
    sectionSlug: "sop-library",
    title: "More Info Request from Insurance",
    excerpt: "Resubmit, redirect, or articulate why info is unnecessary.",
    portal: "internal",
    roles: ["cm"],
    updatedAt: UPDATED,
    blocks: [
      ul([
        "Check if already submitted — if yes, resubmit or redirect",
        "If unnecessary, articulate why professionally",
        "If needed from client, follow Client Info Request SOP",
      ]),
    ],
  }),
  defineArticle({
    slug: "requested-supplements",
    sectionSlug: "sop-library",
    title: "Requested Supplements",
    excerpt: "Monday subtask triggered supplement workflow.",
    portal: "internal",
    roles: ["cm"],
    updatedAt: UPDATED,
    blocks: [
      p("Triggered in Monday subtask. Checklist: sufficient files, photos, description."),
      ul(["Create", "Submit", "Negotiate", "Follow Two-Day Contact Cycle", "Inform client once supplement settles"]),
    ],
  }),
  defineArticle({
    slug: "free-money-supplements",
    sectionSlug: "sop-library",
    title: "Free Money Supplements",
    excerpt: "Post-completion scope review — NOT YET ENACTED with clients.",
    portal: "internal",
    roles: ["cm", "tl"],
    updatedAt: UPDATED,
    blocks: [
      callout("warning", "NOT YET ENACTED WITH CLIENTS. Do not initiate without TL approval and confirmed client enrollment."),
      ul([
        "Upon or near project completion, review documentation across entire lifecycle",
        "Identify additional claim value",
        "Create, submit, negotiate; follow Two-Day Contact Cycle",
        "Inform client once supplement settles",
      ]),
    ],
  }),
  defineArticle({
    slug: "coc-sop",
    sectionSlug: "sop-library",
    title: "Certificate of Completion (COC)",
    excerpt: "COC link workflow and Jotform.",
    portal: "internal",
    roles: ["cm"],
    updatedAt: UPDATED,
    blocks: [
      ul([
        "COC column has link clients use for policyholder signature",
        "Clients must use our COC if they want TCN to handle it",
        "COC auto-emails adjuster, client, policyholder receipt, and CM team",
      ]),
      link(EXTERNAL_LINKS.cocJotform, "COC Jotform Link"),
    ],
  }),
  defineArticle({
    slug: "public-adjuster-sops",
    sectionSlug: "sop-library",
    title: "Public Adjuster SOPs",
    excerpt: "TL approval, client approval, PA sheet, and Monday handoff.",
    portal: "internal",
    roles: ["cm", "pa", "tl"],
    updatedAt: UPDATED,
    blocks: [
      ul([
        "CM requests TL approval via \"Escalated to PA\" button in Estimator Dash",
        "CM gets client approval",
        "CM completes PA sheet (column next to Escalate to PA button)",
        "CM/TL handoff to PA via assignment in Estimator Column",
        "PA gets policyholder contract signed (state-dependent)",
        "Execute to settlement or withdrawal; if stuck, appraiser SOPs",
      ]),
    ],
  }),
  defineArticle({
    slug: "appraiser-sops",
    sectionSlug: "sop-library",
    title: "Appraiser SOPs",
    excerpt: "Appraisal demand, client approval templates, attorney escalation path.",
    portal: "internal",
    roles: ["cm", "appraiser", "tl"],
    updatedAt: UPDATED,
    blocks: [
      ul([
        "CM requests TL approval via \"Escalated to Appraisal\" button",
        "CM obtains client approval using appraisal template",
        "CM files Appraisal Demand Letter to insurance",
        "If insurance denies: TL + client approval for court-ordered appraisal ($5K–$15K)",
        "CM/TL handoff to Appraiser via Monday assignment",
        "Appraiser obtains signed contract from policyholder",
        "Execute until Appraisal Award or withdrawal",
      ]),
    ],
  }),
  defineArticle({
    slug: "estimate-creation-sop",
    sectionSlug: "sop-library",
    title: "Estimate Creation SOP",
    excerpt: "Deliver comprehensive estimate within 24 hours of complete documentation.",
    portal: "internal",
    roles: ["cm"],
    updatedAt: UPDATED,
    blocks: [
      p("Goal: deliver comprehensive, accurate estimate within 24 hours of complete documentation."),
      h(3, "1. Claim Review"),
      p("Review all documentation, identify missing info immediately, contact client, review policy and endorsements."),
      h(3, "2. Estimate Creation"),
      p("Use Xactimate and/or T&M. Include all line items with justification, photos, code citations, O&P where applicable, detailed scope narrative."),
      h(3, "3. Client Delivery"),
      p("Upload to portal, send update, schedule review call if needed, get client approval before submitting to insurance."),
      h(3, "Red Flags"),
      p("Rushing estimates = more pushback later. Clients pushing for unethical scope inflation leads to lower settlements and disgruntled clients."),
    ],
  }),
  defineArticle({
    slug: "negotiation-settlement-sop",
    sectionSlug: "sop-library",
    title: "Negotiation & Settlement Process",
    excerpt: "7-step process targeting 21–35 day close.",
    portal: "internal",
    roles: ["cm"],
    updatedAt: UPDATED,
    blocks: [
      p("Goal: maximize settlement efficiently. Close within 21–35 days of estimate submission."),
      h(3, "Step 1 — Submit to Insurance"),
      p("Client approves, file moves to Stage 2, submit to adjuster, set 48hr follow-up reminder."),
      h(3, "Step 2 — Initial Adjuster Response"),
      p("Within 48 hours. If no response, follow up immediately (phone required)."),
      h(3, "Step 3 — Prepare Negotiation Strategy"),
      p("Review objections, gather photos, code citations, vendor quotes, policy language."),
      h(3, "Step 4 — Negotiation Process"),
      p("Respond within 24 hours, provide justification, stay professional but firm, update client every 2 days minimum."),
      h(3, "Step 5 — Escalation Decision (Day 7–14)"),
      p("Continue if progress; if stalled with TL approval: invoke PA, escalation letter, appraisal deadline, notify client."),
      h(3, "Step 6 — Settlement Agreement"),
      p("Review final offer with client, get approval, document settlement amount."),
      h(3, "Step 7 — Close-Out"),
      p("Update status to Completed, client pays final invoice."),
    ],
  }),
  defineArticle({
    slug: "second-inspection-rule",
    sectionSlug: "sop-library",
    title: "2nd Inspection/Estimate Rule",
    excerpt: "Fee recalculation when carrier reinspection exceeds TCN estimate.",
    portal: "internal",
    roles: ["cm", "tl"],
    updatedAt: UPDATED,
    blocks: [
      p("If insurance sends another adjuster and their revised estimate exceeds TCN estimate, CM only gets minimum estimate fee. Negotiation invoices based on 2nd insurance amount as initial carrier estimate."),
      p("Example: Carrier $5K → TCN $10K → Carrier 2nd $20K (min est fee) → Settlement $25K (15% of $5K increase above $20K)."),
      p("If we initiated reinspection, business as usual."),
    ],
  }),
  defineArticle({
    slug: "tl-new-claim-assignment",
    sectionSlug: "sop-library",
    title: "TL: New Claim Assignment",
    excerpt: "Assign within 1 business hour based on capacity and skillset.",
    portal: "internal",
    roles: ["tl"],
    updatedAt: UPDATED,
    blocks: [
      p("Assign within 1 business hour based on Team Member Board: capacity, skillset, geography, client alignment."),
    ],
  }),
  defineArticle({
    slug: "tl-kpi-reviews",
    sectionSlug: "sop-library",
    title: "TL: KPI Reviews",
    excerpt: "Weekly monitoring of speed, settlement lift, and file movement.",
    portal: "internal",
    roles: ["tl"],
    updatedAt: UPDATED,
    blocks: [
      p("Weekly monitoring of speed metrics, settlement lift, and file movement compliance."),
    ],
  }),
  defineArticle({
    slug: "exec-accidental-direct-pay",
    sectionSlug: "sop-library",
    title: "Exec: Accidental Direct Pay",
    excerpt: "Identify, notify, facilitate endorsement, track resolution.",
    portal: "internal",
    roles: ["exec"],
    updatedAt: UPDATED,
    blocks: [
      ul(["Identify immediately", "Notify all parties", "Facilitate endorsement", "Track resolution"]),
    ],
  }),
];
