import { callout, defineArticle, h, link, p, ul } from "@/lib/help-center/builder";
import { EXTERNAL_LINKS } from "@/lib/help-center/videos";

const UPDATED = "2026-06-08";

export const documentationArticles = [
  defineArticle({
    slug: "intake-checklist",
    sectionSlug: "required-documentation",
    title: "Intake Upload Checklist",
    excerpt: "Required files, photos, and information for every new project submission.",
    portal: "client",
    updatedAt: UPDATED,
    blocks: [
      h(2, "Required for Every Intake"),
      ul([
        "Contract with ICA, AOB, and Appraiser Authorization",
        "Sufficient files (ideally not screenshots of documents)",
        "Sufficient photos",
        "Sufficient job notes (description and job site distance from office for supervisory fees and trip charges)",
        "Sketch and measurements with L×W×H",
        "Insurance estimate (if available)",
        "Policy",
        "Claim number",
        "Adjuster name, phone, and email",
      ]),
      h(3, "If Mitigation"),
      ul([
        "Demo sheets",
        "Material sheets",
        "Dry logs and moisture mapping",
      ]),
      h(3, "Supplement Requests"),
      ul([
        "Additional uploads of pics, videos, and docs",
        "Description of supplement request",
      ]),
    ],
  }),
  defineArticle({
    slug: "field-documentation-overview",
    sectionSlug: "required-documentation",
    title: "Field Documentation Overview",
    excerpt: "Why thorough field documentation drives stronger estimates and faster approvals.",
    portal: "client",
    updatedAt: UPDATED,
    blocks: [
      callout(
        "info",
        "The better the documentation from the field, the stronger the estimate we can build for your company.",
      ),
      p("We are not on-site — you are. The photos, videos, and notes you capture become the evidence we use to:"),
      ul([
        "Write accurate estimates",
        "Justify full scope of work",
        "Negotiate with insurance",
        "Reduce back-and-forth inspections",
        "Help get projects approved faster",
      ]),
      p("If something isn't documented clearly, insurance usually assumes it doesn't exist."),
    ],
  }),
  defineArticle({
    slug: "field-documentation-principles",
    sectionSlug: "required-documentation",
    title: "General Documentation Principles",
    excerpt: "Wide photos first, detail second — capture proof, not perfection.",
    portal: "client",
    updatedAt: UPDATED,
    blocks: [
      ul([
        "More photos are always better than fewer",
        "Take photos before work begins whenever possible",
        "Wide photos first, detail photos second",
        "Show how areas connect to each other",
        "When unsure — take another photo",
      ]),
      p("You are not trying to take perfect photos — just clear proof of conditions."),
    ],
  }),
  defineArticle({
    slug: "interior-documentation",
    sectionSlug: "required-documentation",
    title: "Interior Documentation",
    excerpt: "Seven-step interior photo and measurement guide.",
    portal: "client",
    updatedAt: UPDATED,
    blocks: [
      h(3, "1. Start With the Whole Room"),
      p("Stand near the doorway and take wide photos using the .5 lens (zoomed out): all four corners, ceiling, and floor."),
      h(3, "2. Show the Damage in Context"),
      p("Wide photos showing damaged area, surrounding materials, and nearby undamaged areas."),
      h(3, "3. Take Detail Photos"),
      p("Switch to 1x lens. Photograph stains, cracks, swelling, moisture effects, and damaged finishes from multiple angles."),
      h(3, "4. Show Continuous Materials"),
      p("Photograph flooring, paint, and trim continuity across rooms when materials run room to room."),
      h(3, "5. Photograph Items That Must Be Moved"),
      p("Capture toilets, cabinets, appliances, doors, baseboards, and large contents that must be shifted for work."),
      h(3, "6. Quick Video Walkthrough"),
      p("Using .5 lens, do a slow 30–60 second walkthrough describing room names, visible damage, and anything unusual."),
      h(3, "7. Measurements"),
      p("Simple sketches with length, width, height, and how rooms connect. Rough measurements are still helpful."),
    ],
  }),
  defineArticle({
    slug: "exterior-roof-documentation",
    sectionSlug: "required-documentation",
    title: "Exterior & Roof Documentation",
    excerpt: "Elevation overviews, damage sequences, and roof slope coverage.",
    portal: "client",
    updatedAt: UPDATED,
    blocks: [
      h(3, "Exterior Overview"),
      p("Wide photos of front, rear, left side, and right side."),
      h(3, "Damage Areas"),
      p("For each area: wide photo showing location, mid-range photo, and close-up detail photo."),
      h(3, "Roof Photos (If Accessible)"),
      ul([
        "Each slope, valleys, flashing areas",
        "Vents and penetrations, gutters and edges",
        "Surrounding areas if shingles or materials are disturbed",
      ]),
      h(3, "Access & Safety Conditions"),
      p("Document steep roofs, height challenges, limited access, and obstacles around the structure."),
    ],
  }),
  defineArticle({
    slug: "mitigation-documentation",
    sectionSlug: "required-documentation",
    title: "Mitigation Documentation",
    excerpt: "Demo sheets, dry logs, moisture maps, and equipment photos.",
    portal: "client",
    updatedAt: UPDATED,
    blocks: [
      p("When applicable, upload:"),
      ul([
        "Demo sheets",
        "Material sheets",
        "Dry logs",
        "Moisture maps",
        "Equipment setup photos",
      ]),
      p("These greatly improve estimate accuracy on water, mold, and sewage projects."),
    ],
  }),
  defineArticle({
    slug: "commonly-missed-photos",
    sectionSlug: "required-documentation",
    title: "Commonly Missed Photos",
    excerpt: "Adjacent rooms, transitions, protection, and access pathways.",
    portal: "client",
    updatedAt: UPDATED,
    blocks: [
      p("If possible, include:"),
      ul([
        "Adjacent rooms",
        "Undamaged matching materials",
        "Transitions between spaces",
        "Protection setup",
        "Equipment placement",
        "Pathways used to access work areas",
      ]),
      p("These details often answer insurance questions before they are asked."),
    ],
  }),
  defineArticle({
    slug: "documentation-final-check",
    sectionSlug: "required-documentation",
    title: "Documentation Final Check",
    excerpt: "Could someone who has never been on-site understand the job from your photos?",
    portal: "client",
    updatedAt: UPDATED,
    blocks: [
      callout(
        "success",
        "Before leaving site, ask: Could someone who has never been here understand the job from these photos and videos? If not, take a few more wide shots.",
      ),
      p(
        "Good documentation allows us to build stronger estimates, reduce delays, limit re-inspections, support negotiations, and move claims forward faster. A few extra minutes documenting in the field saves significant time later.",
      ),
      p("You don't need to document perfectly — just thoroughly."),
    ],
  }),
  defineArticle({
    slug: "plnar-tool",
    sectionSlug: "required-documentation",
    title: "PLNAR (Optional Tool)",
    excerpt: "Recommended 3D documentation tool — not required.",
    portal: "client",
    updatedAt: UPDATED,
    blocks: [
      callout("info", "NOT REQUIRED — RECOMMENDATION ONLY."),
      p(
        "PLNAR works with any smartphone (no LiDAR required). For interiors, photograph room corners and do a quick 30-second to 1-minute video walkthrough. It generates 2D/3D sketches with embedded photos, reports, and shareable links. Exterior capabilities available.",
      ),
      ul([
        "Free 30-day trial",
        "When signing up, let them know The Claims Ninja sent you",
      ]),
      link(EXTERNAL_LINKS.plnar, "Visit PLNAR"),
    ],
  }),
  defineArticle({
    slug: "mit-demo-dry-log-tracking",
    sectionSlug: "required-documentation",
    title: "Mit Demo & Dry Log Tracking",
    excerpt: "Enhanced mitigation documentation tools — coming soon.",
    portal: "client",
    updatedAt: UPDATED,
    hidden: true,
    blocks: [
      callout(
        "warning",
        "Mitigation demo and dry log tracking guidance is being finalized. Check back for updates or contact your Claims Manager for current mitigation documentation standards.",
      ),
    ],
  }),
];
